env: "prod"

http-server:
  host: "0.0.0.0"
  port: 8000
  writeTimeout: 10s
  readTimeout: 10s
  maxHeaderMegabytes: 1

postgres:
  host: "postgres"
  port: 5432
  user: "pguser"
  db: "devdb"
  ssl: disable


user-logs-dir: "./assets/user_logs/"